NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

VERSION="2.0.0"

ACCOUNTS=[
"GBPBUOS7DG7IOK3CCX3TPVLG4PW44C7J5M4VEXREYSM7EOQAGEYPY7QV"
]

HOME_DOMAIN="sike-project.vercel.app"

[DOCUMENTATION]
ORG_NAME="SIKE"
ORG_URL="https://sike-project.vercel.app"
ORG_LOGO="https://sike-project.vercel.app/logo.png"
ORG_DESCRIPTION="SIKE is a community-driven digital token built on the Stellar network."

[[CURRENCIES]]
code="SIKE"
issuer="GBPBUOS7DG7IOK3CCX3TPVLG4PW44C7J5M4VEXREYSM7EOQAGEYPY7QV"
name="SIKE"
desc="SIKE is a Stellar-based community token."
image="https://sike-project.vercel.app/logo.png"
home_domain="sike-project.vercel.app"
fixed_number=901000000
display_decimals=7
status="live"