NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

VERSION="2.0.0"

ACCOUNTS=[
"GBPBUOS7DG7IOK3CCX3TPVLG4PW44C7J5M4VEXREYSM7EOQAGEYPY7QV"
]

HOME_DOMAIN="sike-project.vercel.app"

[DOCUMENTATION]
ORG_NAME="SIKE"
ORG_URL="https://sike-project.vercel.app"
ORG_LOGO="https://sike-project.vercel.app/logo_sec.png"
ORG_DESCRIPTION="SIKE is a Stellar-based utility reward ecosystem where users earn tokens by completing meaningful tasks and contributing value."

[[CURRENCIES]]
code="SIKE"
issuer="GBPBUOS7DG7IOK3CCX3TPVLG4PW44C7J5M4VEXREYSM7EOQAGEYPY7QV"
status="live"
name="SIKE"
desc="SIKE is a utility reward token powering a task-based ecosystem built on the Stellar network."
image="https://sike-project.vercel.app/logo_sec.png"
home_domain="sike-project.vercel.app"
display_decimals=7
